### ISSUE TITLE
After using update.sh, everything is gone

### ISSUE THREAD

**Issue by Schnookeuz** [mailcow/mailcow-dockerized#1257]
Hi,

i got a very horrific problem: After updating my instance as every month with the update.sh script, everything is gone. All domains, settings, mailboxes, users... It's like I installed it fresh.
During the update-process, there were no errors. as the script says, I have not executed "docker system prune" since the update, so i think i can get my data back? I know simply nothing about docker, can only follow manuals.

**Comment by andryyy** [comment]
It would not delete any volumes.

You can give me access via info@servercow.de to check this.

**Comment by longtawan** [comment]
Hi andryyy,

ist there a solution yet?
Cause the same happened with my mail accounts...
Thnx and good morning

**Comment by andryyy** [comment]
He just changed the project name, so the volume names changed.

This does not happen automatically.

**Comment by longtawan** [comment]
Don't understand...
Just started update.sh
Is it possible to send you data as you asked Schnookeuz ?

**Comment by andryyy** [comment]
Yes. 👍

**Comment by andryyy** [comment]
Damn:

```
Dashes and underscores in project names are no longer stripped out.
```

**Comment by longtawan** [comment]
Means?

**Comment by andryyy** [comment]
Please run:
```
docker-compose down
sed -i '/COMPOSE_PROJECT_NAME=.*/{s/-//}' mailcow.conf
sed -i '/COMPOSE_PROJECT_NAME=.*/{s/_//}' mailcow.conf
docker-compose up -d
```

**Comment by Schnookeuz** [comment]
Thanks a lot andryyy for the fast help!
For me, this can be closed.

**Comment by longtawan** [comment]
Unfortunately not for me :-(
Still nothing is there

**Comment by andryyy** [comment]
We fixed it. COMPOSE_PROJECT_NAME was COMPOSEPROJECT_NAME, sorry.

**Comment by cataldoc** [comment]
Uhhh I have this issue too, everything disappeared

in mailcow.conf I have

```
# Fixed project name
COMPOSEPROJECT_NAME=mailcowdockerized
```

if I change it to COMPOSE_PROJECT_NAME when I try to start it I get this error

```
ERROR: cannot create network 7d8bf35ef04ba23b0b91ba55738cc581b2fe24bcc49deb144f4aab5c4bbc7082 (br-7d8bf35ef04b): conflicts with network 8792eddcf0aea14ef49609de8151e792ea55b5860a84e0686bace02f06e2e467 (br-8792eddcf0ae):
networks have overlapping IPv4
```

**Comment by andryyy** [comment]
Please check exactly what was recommended: stop and remove the existing containers.

**Comment by cataldoc** [comment]
I did it as first thing as it was suggested:

```
docker-compose down
sed -i '/COMPOSE_PROJECT_NAME=.*/{s/-//}' mailcow.conf
sed -i '/COMPOSE_PROJECT_NAME=.*/{s/_//}' mailcow.conf
docker-compose up -d
```

but doesn't fix it :'(

**Comment by andryyy** [comment]
It has active containers and didn’t remove the existing network. You can mail me credentials and I will fix it. :-)

**Comment by cataldoc** [comment]
tnx a lot... sent to: info@servercow.de

**Comment by next-direction** [comment]
Just stumbled over the same issue. 
For me in conclusion the issue was, that this line was completely missing in mailcow.conf:
COMPOSE_PROJECT_NAME=mailcowdockerized

After running update.sh again, it added it but with COMPOSEPROJECT_NAME=... 
After fixing this it startet with old data available.

Thanks for help in this thread to figure this out!

**Comment by phipag** [comment]
Yes, for me the update.sh also added the wrong line. I did it manually too.

**Comment by andryyy** [comment]
Sorry, I am not sure when I added COMPOSEPROJECT_NAME. :-(

**Comment by phipag** [comment]
No problem. Keep up your great work. Mailcow is the best mailing software solution i know.

**Comment by axd** [comment]
For me `update.sh` did not add the variable in mailcow.conf, so I was afraid that everything was wiped, but after a search of this issue, I found that in the new version of MC you have to add the `COMPOSE_PROJECT_NAME=mailcowdockerized` variable in the file config. This bring things up again.

Thanks for the help.
