### ISSUE TITLE
Disable sender check for * (+ alias domains) Not Working

### ISSUE THREAD

**Issue by th3technician** [mailcow/mailcow-dockerized#1652]
So i have tried the new feature of "Disable sender check for * (+ alias domains)" in the drop list of editing a mailbox account and its not working, It only works by following [this guide](https://mailcow.github.io/mailcow-dockerized-docs/u_e-postfix-disable_sender_verification/)

**Comment by andryyy** [comment]
I did and it works.

Needs more info.

**Comment by andryyy** [comment]
You'd need to revert any custom changes, upgrade mailcow and provide image versions (esp. Postfix). I just verified it is indeed working.

**Comment by th3technician** [comment]
I just went to a mailbox account and in the drop list i selected "Disable sender check for * (+ alias domains)" then i tried to use the mailbox account in my mailer with another sender email and it didn't work when i debugged postfix logs it gave 
`<email1@domain.com>: Sender address rejected: not owned by user email2@domain.com;`

But when i used the guide using the check_sasl file method it worked fine

**Comment by andryyy** [comment]
I need image infos and the last git commit you are on. I cannot verify this.

**Comment by th3technician** [comment]
Imma do one more test today and update this ticket if error still occurs

**Comment by Finn10111** [comment]
Is issue #1674 a duplicate of this one? I am also on the latest commit but I can't disable or modify the sender check. Postfix Container version is 1.21 .

**Comment by andryyy** [comment]
The image was fixed. Needs more info if it fails for you.

**Comment by Finn10111** [comment]
What information do you need? 

```
docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
mailcow/sogo        1.34                d1a4855bd2c0        4 days ago          465MB
<none>              <none>              c763686d1ad3        4 days ago          405MB
mariadb             10.2                a3a0b2e0a030        5 days ago          359MB
mailcow/postfix     1.21                830653331a37        6 days ago          222MB
memcached           alpine              40eaba0c57cc        7 days ago          8.7MB
mailcow/acme        1.37                78b191581bf2        2 weeks ago         53MB
mailcow/clamd       1.13                f955366517f6        2 weeks ago         92MB
redis               4-alpine            08bef618c30a        2 weeks ago         28.7MB
mailcow/dovecot     1.33                e2af38fa2e9b        2 weeks ago         529MB
mailcow/rspamd      1.24                0acda61f33f5        2 weeks ago         268MB
mailcow/netfilter   1.19                cf07f8adc116        3 weeks ago         69.7MB
nginx               mainline-alpine     36f3464a2197        4 weeks ago         18.6MB
php                 7.2-fpm-alpine3.7   2f455392da29        4 weeks ago         78.7MB
debian              stretch-slim        184356db7df7        5 weeks ago         55.3MB
alpine              3.8                 11cd0b38bc3c        6 weeks ago         4.41MB
alpine              3.6                 da579b235e92        6 weeks ago         4.03MB
mailcow/phpfpm      1.18                39330e4aabd2        7 weeks ago         301MB
mailcow/watchdog    1.19                95ea9a765ca8        7 weeks ago         61MB
mailcow/dockerapi   1.13                10854ca0292d        7 weeks ago         95.5MB
mailcow/unbound     1.1                 4b89d5b2bb6f        4 months ago        18.7MB
robbertkl/ipv6nat   latest              20acd6529e3e        6 months ago        21.6MB
```



```
cat data/conf/postfix/sql/mysql_virtual_sender_acl.cf

user = mailcow
password = password
hosts = mysql
dbname = mailcow
# First select queries domain and alias_domain to determine if domains are active.
query = SELECT goto FROM alias
  WHERE address='%s'
    AND active='1'
    AND (domain IN
      (SELECT domain FROM domain
        WHERE domain='%d'
          AND active='1')
      OR domain in (
        SELECT alias_domain FROM alias_domain
          WHERE alias_domain='%d'
            AND active='1'
      )
    )
  UNION
  SELECT logged_in_as FROM sender_acl
    WHERE send_as='@%d'
      OR send_as='%s'
      OR send_as='*'
      OR send_as IN (
        SELECT CONCAT('@',target_domain) FROM alias_domain
          WHERE alias_domain = '%d')
      OR send_as IN (
        SELECT CONCAT('%u','@',target_domain) FROM alias_domain
          WHERE alias_domain = '%d')
      AND logged_in_as NOT IN (
        SELECT goto FROM alias
          WHERE address='%s')
  UNION
  SELECT username FROM mailbox, alias_domain
    WHERE alias_domain.alias_domain = '%d'
      AND mailbox.username = CONCAT('%u','@',alias_domain.target_domain)
      AND mailbox.active ='1'
      AND alias_domain.active='1'
```

Running `docker-compose exec postfix-mailcow postalias -q finn@exmaple.local mysql:/opt/postfix/conf/sql/mysql_virtual_sender_acl.cf` does not produce any output. 

I have added a mailbox which I want to use for relaying mails from my hosts in my local network. Am I doing something wrong?

**Comment by andryyy** [comment]
It does work different when you relay mails. I don't think you are authenticating, do you?

What is your exact configuration? Where do you authenticate, when do you relay, is this a "relayed" domain (backup mx) etc.

**Comment by Finn10111** [comment]
I have a few servers in my local network which send mails via another local server. On this local mailserver I have running postfix with this configuration:

main.cf:
```
relayhost = [mailcow.pimux.de]:587
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/smtp_auth
smtp_sasl_security_options = noanonymous
smtp_use_tls = yes
```
smtp_auth:
```
mailcow.pimux.de        relaying@finnchristiansen.de:password
```

This local mail server accepts mails from my other local servers but it is not able to send this mail to the mailcow server because of the different sender domain I think (pve.local for example).

mail.log:
```
Aug 21 20:31:08 vm1 postfix/smtp[2339]: DBEDDBFD14: to=<kontakt@finnchristiansen.de>, relay=mailcow.pimux.de[193.30.122.8]:587, delay=1.1, delays=0.07/0.11/0.79/0.11, dsn=5.7.1, status=bounced (host mailcow.pimux.de[193.30.122.8] said: 553 5.7.1 <root@pve.local>: Sender address rejected: not owned by user relaying@finnchristiansen.de (in reply to RCPT TO command))
```

I know pve.local isn't a valid FQDN but because of this I am trying to disable the sender check.

**Comment by Finn10111** [comment]
The problem is gone after updating to the latest version (commit 8056ed21af52035e1b4ba71c4d7ae1c61653cafa). I can't exactly say which commit fixed this problem but thank you all! 

Can this issue be closed now or are other people still having problems?
