### ISSUE TITLE
Nextcloud sending Emails

### ISSUE THREAD

**Issue by JonnyFPV** [mailcow/mailcow-dockerized#1814]
Hi,

i got a problem with sending emails with nextcloud Web GUI and mailcow.

Sending any Testemail from Nextcloud Web GUI for password reset and test configuration woks good.

But if i ant to send an email for shared folder the email didnt arrived. Postfix Log:

  | NOQUEUE:  reject: RCPT from unknown[XXX.XXX.XXX.XXX]: 554 5.7.1  <xxx@gmail.com>: Relay access denied;  from=<nextcloud@xxx.de> to=<xxx@gmail.com>  proto=ESMTP helo=<xxx.de>
-- | --

If i send and password reset request over the nextcloud GUI the email is sending fine. Email Configuration in Nextcloud is over SMTP with authentification.  

please note the "xxx" values are censored. 
--------------------------------------------------------------------
so and second problem is i see warings: warning: hostname xxxxx.xxxx.de does not resolve to address xxx.xxx.xxx.xxx

but reverse dns and dns lookup points to the correct ip adress and reverse dns to the FQDN. Hostname configuration on my VServer is set correctly. so i searched around the web and didnt figured it out. :-(

please any help :)

**Comment by JonnyFPV** [comment]
So one issue is resolved: I put in the nextcloud conf in web GUI for email sending the 172.22.1.1 ip instead of the domain name. So this is working now :) 

But for the warning message I didn’t find any solution

**Comment by andryyy** [comment]
How did you install Nextcloud? The helper script uses "postfix" as smtp host by default. But this only works on the same network. Is this an external Nextcloud container?

The reverse dns warning are logged by postfix-mailcow? For which server? For multiple servers or only this particular IP? Please paste the full log or we cannot help. :-/

**Comment by JonnyFPV** [comment]
Hi. 

Mailcow newest docer version. 
Reverse proxy with apache2 
Nextcloud installed in apache2 on same server 

The warning comes from postfix mailcow ui debugging log yes. 

What logs do you Need exactly ? Thank you for your help :)

**Comment by andryyy** [comment]
Do you see this warning for multiple names or only for this single (censored) name? => `warning: hostname xxxxx.xxxx.de does not resolve to address xxx.xxx.xxx.xxx`

You can try to run this on your host:
```
dig xxxxx.xxxx.de +short
dig xxxxx.xxxx.de +short @1.1.1.1
# Command below in the mailcow-dockerized folder
docker-compose exec watchdog-mailcow dig xxxxx.xxxx.de +short
```

Does it return always the same output?

**Comment by JonnyFPV** [comment]
no i get some other IP Warning. But i think this is from Spammers they want to connect to my server?


```
1.10.2018, 20:42:06 | info | disconnect from unknown[93.174.93.228] ehlo=1 auth=0/1 rset=1 quit=1 commands=3/4
-- | -- | --
1.10.2018, 20:42:06 | warning | warning: unknown[93.174.93.228]: SASL LOGIN authentication failed: UGFzc3dvcmQ6
1.10.2018, 20:42:04 | info | Anonymous TLS connection established from unknown[93.174.93.228]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
1.10.2018, 20:42:04 | info | connect from unknown[93.174.93.228]
1.10.2018, 20:42:04 | warning | warning: hostname hosted-by.rainbownetworks.net does not resolve to address 93.174.93.228: Name or service not known
1.10.2018, 20:41:39 | info | statistics: max cache size 1 at Oct  1 20:38:15
1.10.2018, 20:41:39 | info | statistics: max connection count 1 for (smtpd:192.30.252.198) at Oct  1 20:38:15
1.10.2018, 20:41:39 | info | statistics: max connection rate 1/60s for (smtpd:192.30.252.198) at Oct  1 20:38:15
```

and your commands above always gives me the same IP of my server back. So i think its fine. This Warning from my domain and IP was because of nextcloud tried to send emails over smtp. Now i changed it see above and its working now. i dindt see any warning from mydomain and ip again :-) 

sorry this was missconfiguration i think :-)

**Comment by andryyy** [comment]
Yes, some names/IPs might be misconfigured and it is indeed most likely spam. :-)

**Comment by GAlexMES** [comment]
I am running into exactly the same problem.

> dig xxxxx.xxxx.de +short
> dig xxxxx.xxxx.de +short @1.1.1.1
> docker-compose exec watchdog-mailcow dig xxxxx.xxxx.de +short

All three are showing the same IP for me.

But when I want to configure nextcloud to use the mailcow smtp, I get:

`Connection could not be established with host mail.xxx.de `

And the Mailcow postifx log is telling me:


> 24.1.2019, 15:12:02 | info | disconnect from unknown[173.xxx.xxx.26] commands=0/0
> 24.1.2019, 15:12:02 | info | lost connection after CONNECT from unknown[173.xxx.xxx.26]
> 24.1.2019, 15:12:02 | warning | warning:  TLS library problem: error:14094418:SSL routines:ssl3_read_bytes:tlsv1  alert unknown ca:../ssl/record/rec_layer_s3.c:1399:SSL alert number 48:
> 24.1.2019, 15:12:02 | info | SSL_accept error from unknown[173.xxx.xxx.26]: -1
> 24.1.2019, 15:12:02 | info | connect from unknown[173.xxx.xxx.26]
> 24.1.2019, 15:12:02 | warning | warning: hostname xxx.de does not resolve to address 173.xxx.xxx.26

Any ideas?

**Comment by andryyy** [comment]
What does your NC mail config look like?

**Comment by GAlexMES** [comment]
Mode: SMTP
Encryption: SSL/TLS
Sender: admin@xxx.de
Authentication: Login
Server: mail.xxx.de : 465

Additional Info:

I am running:

- mailcow-dockerized in the current version.
- NC: 14.0.6 not dockerized

**Comment by andryyy** [comment]
Are the certificates on port 465 correct/trusted? Port 587 is not working, too?

**Comment by GAlexMES** [comment]
Certificates should be fine. At least I have no problem with them on any other device. But I could check it.

I get a different error for STARTTLS. But SSL/TLS on 587 is the same.

**Comment by andryyy** [comment]
Can you mail me your server name to info@servercow.de?

------ Originalnachricht ------
Von: "Alexander Brennecke" <notifications@github.com>
An: "mailcow/mailcow-dockerized" <mailcow-dockerized@noreply.github.com>
Cc: "André Peters" <andre.peters@debinux.de>; "Comment" 
<comment@noreply.github.com>
Gesendet: 24.01.2019 15:28:42
Betreff: Re: [mailcow/mailcow-dockerized] Nextcloud sending Emails 
(#1814)

**Comment by GAlexMES** [comment]
According to https://www.sslshopper.com/ssl-checker.html the Cert is not valid.

I din't knew, that I need to provide a cert for the given port.

**Comment by andryyy** [comment]
See the docs, you need to either configure your reverse proxy to let acme-mailcow handle the Let's Encrypt stuff or use a post-hook to copy the certs to data/assets/ssl. :)

**Comment by GAlexMES** [comment]
It is actually running on 80, that is why I thought that a cert was created.
