### ISSUE TITLE
Cannot send email

### ISSUE THREAD

**Issue by jonrysimbolon** [mailcow/mailcow-dockerized#4003]
i'm sorry cause deleted this templet.

my problem is can't sending email to anyone.
i get error 405 not allowed in console (inspect element) when i send the mail.
and i get "not allowed in state 1" on browser.

![Screen Shot 2021-02-25 at 20 36 10](https://user-images.githubusercontent.com/26339624/109161650-e465fe80-77a9-11eb-96be-a4d0d8b198eb.png)
![Screen Shot 2021-02-25 at 20 36 37](https://user-images.githubusercontent.com/26339624/109161656-e760ef00-77a9-11eb-8672-808efd70c48e.png)
![Screen Shot 2021-02-25 at 20 37 58](https://user-images.githubusercontent.com/26339624/109161759-06f81780-77aa-11eb-9669-d24cc9938ee1.png)

**Comment by dragoangel** [comment]
If you want get support use telegram or forum channels. Github not best place for it. Not add bugs where there no any. You not providing any real details or troubleshooting steps from your side to help you here, e.g:

- do dovecot g postfix working at all?
- do docker internal dns resolving working?
- can you send mail over smtp or read over imap?
- what postfix logs display when you face error?
- etc and so on.

Your screenshot totally not answering any of this questions.

**Comment by kreditor0815** [comment]
## Summary

Im currently having the same issue after updating ubuntu and changing the storage from glusterfs to nfs. After that i also updated mailcow to the current version.
My problem is that i can not send any mails via SoGo or attached Exchange ActiveSync devices. Cant tell if other protocals are broken aswell, because i only user SoGo Webmail oder Exchange Active-Sync Devices/Clients. 
On a current Outlook setup, all mails remain in the outbox.
Im also not receiving any mails since that point of time.

## Logs

In the WebUI under Logs -> Postfix i noticed a critical line stating:
"fatal: Queue report unavailable - mail system is down"
When i try to send a mail with sogo and i do get those error messages @jonrysimbolon attached to his post, i also notice an output from the sogo container: 
"sogod [73]: [ERROR] <0x0x55658e506af0[SOGoMailer]> Could not connect to the SMTP server smtp://postfix:588/?TLS=YES&tlsVerifyMode=none"
I also noticed those messages from sogos:
"19:05:20.283 sogod[78:78] parseTimeZone: cannot parse time notation 'GMT'"
and
"27.03.2021, 19:05:26 | notice | [78]: [WARN] <0x0x55d22b074c50[SOGoWebDAVAclManager]> entry '{DAV:}write-content' already exists in DAV permissions table
-- | -- | --
27.03.2021, 19:05:26 | notice | [78]: [WARN] <0x0x55d22b074c50[SOGoWebDAVAclManager]> entry '{DAV:}write-properties' already exists in DAV permissions table
27.03.2021, 19:05:26 | notice | [78]: [WARN] <0x0x55d22b074c50[SOGoWebDAVAclManager]> entry '{DAV:}write' already exists in DAV permissions table"

## Reproduction

I really dont know what exactly ran me into this situation.

## System information


| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04.1 LTS |
| Is Apparmor, SELinux or similar active? | Appamor was disabled by me |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | Hyper-V |
| Server/VM specifications (Memory, CPU Cores) | 8GB RAM, 6 vCores |
| Docker Version (`docker version`) | 19.03.8 |
| Docker-Compose Version (`docker-compose version`) | 1.28.6 |
| Reverse proxy (custom solution) | - |

- Output of `git diff origin/master`:
```
diff --git a/data/Dockerfiles/acme/acme.sh b/data/Dockerfiles/acme/acme.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/acme/expand6.sh b/data/Dockerfiles/acme/expand6.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/clamd/clamd.sh b/data/Dockerfiles/clamd/clamd.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/clamd/tini b/data/Dockerfiles/clamd/tini
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/dovecot/clean_q_aged.sh b/data/Dockerfiles/dovecot/clean_q_aged.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/dovecot/docker-entrypoint.sh b/data/Dockerfiles/dovecot/docker-entrypoint.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/dovecot/imapsync b/data/Dockerfiles/dovecot/imapsync
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/dovecot/maildir_gc.sh b/data/Dockerfiles/dovecot/maildir_gc.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/dovecot/postlogin.sh b/data/Dockerfiles/dovecot/postlogin.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/dovecot/quarantine_notify.py b/data/Dockerfiles/dovecot/quarantine_notify.py
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/dovecot/quota_notify.py b/data/Dockerfiles/dovecot/quota_notify.py
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/dovecot/repl_health.sh b/data/Dockerfiles/dovecot/repl_health.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/dovecot/rspamd-pipe-ham b/data/Dockerfiles/dovecot/rspamd-pipe-ham
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/dovecot/rspamd-pipe-spam b/data/Dockerfiles/dovecot/rspamd-pipe-spam
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/dovecot/sa-rules.sh b/data/Dockerfiles/dovecot/sa-rules.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/dovecot/stop-supervisor.sh b/data/Dockerfiles/dovecot/stop-supervisor.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/dovecot/trim_logs.sh b/data/Dockerfiles/dovecot/trim_logs.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/ejabberd/authenticator b/data/Dockerfiles/ejabberd/authenticator
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/ejabberd/docker-entrypoint.sh b/data/Dockerfiles/ejabberd/docker-entrypoint.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/phpfpm/docker-entrypoint.sh b/data/Dockerfiles/phpfpm/docker-entrypoint.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/postfix/docker-entrypoint.sh b/data/Dockerfiles/postfix/docker-entrypoint.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/postfix/postfix.sh b/data/Dockerfiles/postfix/postfix.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/postfix/rspamd-pipe-ham b/data/Dockerfiles/postfix/rspamd-pipe-ham
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/postfix/rspamd-pipe-spam b/data/Dockerfiles/postfix/rspamd-pipe-spam
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/postfix/smtpd_last_login.sh b/data/Dockerfiles/postfix/smtpd_last_login.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/postfix/stop-supervisor.sh b/data/Dockerfiles/postfix/stop-supervisor.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/postfix/whitelist_forwardinghosts.sh b/data/Dockerfiles/postfix/whitelist_forwardinghosts.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/rspamd/docker-entrypoint.sh b/data/Dockerfiles/rspamd/docker-entrypoint.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/sogo/bootstrap-sogo.sh b/data/Dockerfiles/sogo/bootstrap-sogo.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/sogo/docker-entrypoint.sh b/data/Dockerfiles/sogo/docker-entrypoint.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/sogo/stop-supervisor.sh b/data/Dockerfiles/sogo/stop-supervisor.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/solr/solr.sh b/data/Dockerfiles/solr/solr.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/unbound/docker-entrypoint.sh b/data/Dockerfiles/unbound/docker-entrypoint.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/watchdog/check_mysql_slavestatus.sh b/data/Dockerfiles/watchdog/check_mysql_slavestatus.sh
old mode 100755
new mode 100644
diff --git a/data/Dockerfiles/watchdog/watchdog.sh b/data/Dockerfiles/watchdog/watchdog.sh
old mode 100755
new mode 100644
diff --git a/data/assets/mysql/docker-entrypoint.sh b/data/assets/mysql/docker-entrypoint.sh
old mode 100755
new mode 100644
diff --git a/data/assets/nextcloud/occ b/data/assets/nextcloud/occ
old mode 100755
new mode 100644
diff --git a/data/assets/passwd/generate_passwords.sh b/data/assets/passwd/generate_passwords.sh
old mode 100755
new mode 100644
diff --git a/data/conf/nginx/templates/server_name.template.sh b/data/conf/nginx/templates/server_name.template.sh
old mode 100755
new mode 100644
diff --git a/data/conf/sogo/sogo.conf b/data/conf/sogo/sogo.conf
index 2513f496..5f673a04 100644
--- a/data/conf/sogo/sogo.conf
+++ b/data/conf/sogo/sogo.conf
@@ -26,10 +26,10 @@
     // Domains are isolated, you can define visibility options here.
     // Example:
 
-    // SOGoDomainsVisibility = (
-    //  (domain1.tld, domain5.tld),
-    //  (domain3.tld, domain2.tld)
-    // );
+    SOGoDomainsVisibility = (
+     (-i-redacted-the-list-of-my-domains-here-this-is-not-the-real-content)
+    //  (homezone.xyz, )
+    );
 
     // self-signed is not trusted anymore
     SOGoSieveServer = "sieve://dovecot:4190/?TLS=YES&tlsVerifyMode=none";
diff --git a/data/web/inc/lib/vendor/bshaffer/oauth2-server-php/src/OAuth2/Storage/CouchbaseDB.php b/data/web/inc/lib/vendor/bshaffer/oauth2-server-php/src/OAuth2/Storage/CouchbaseDB.php
old mode 100755
new mode 100644
diff --git a/data/web/inc/lib/vendor/bshaffer/oauth2-server-php/test/lib/OAuth2/Storage/BaseTest.php b/data/web/inc/lib/vendor/bshaffer/oauth2-server-php/test/lib/OAuth2/Storage/BaseTest.php
old mode 100755
new mode 100644
diff --git a/data/web/inc/lib/vendor/bshaffer/oauth2-server-php/test/lib/OAuth2/Storage/Bootstrap.php b/data/web/inc/lib/vendor/bshaffer/oauth2-server-php/test/lib/OAuth2/Storage/Bootstrap.p
hp
old mode 100755
new mode 100644
diff --git a/data/web/inc/lib/vendor/matthiasmullie/minify/bin/minifycss b/data/web/inc/lib/vendor/matthiasmullie/minify/bin/minifycss
old mode 100755
new mode 100644
diff --git a/data/web/inc/lib/vendor/matthiasmullie/minify/bin/minifyjs b/data/web/inc/lib/vendor/matthiasmullie/minify/bin/minifyjs
old mode 100755
new mode 100644
diff --git a/data/web/inc/lib/vendor/paragonie/random_compat/build-phar.sh b/data/web/inc/lib/vendor/paragonie/random_compat/build-phar.sh
old mode 100755
new mode 100644
diff --git a/data/web/inc/lib/vendor/php-mime-mail-parser/php-mime-mail-parser/compile_mailparse.sh b/data/web/inc/lib/vendor/php-mime-mail-parser/php-mime-mail-parser/compile_mailparse.sh
old mode 100755
new mode 100644
diff --git a/data/web/inc/lib/vendor/yubico/u2flib-server/do-source-release.sh b/data/web/inc/lib/vendor/yubico/u2flib-server/do-source-release.sh
old mode 100755
new mode 100644
diff --git a/data/web/inc/lib/vendor/yubico/u2flib-server/examples/cli/u2f-server.phps b/data/web/inc/lib/vendor/yubico/u2flib-server/examples/cli/u2f-server.phps
old mode 100755
new mode 100644
diff --git a/generate_config.sh b/generate_config.sh
old mode 100755
new mode 100644
diff --git a/helper-scripts/backup_and_restore.sh b/helper-scripts/backup_and_restore.sh
old mode 100755
new mode 100644
diff --git a/helper-scripts/check_translations.rb b/helper-scripts/check_translations.rb
old mode 100755
new mode 100644
diff --git a/helper-scripts/mailcow-reset-admin.sh b/helper-scripts/mailcow-reset-admin.sh
old mode 100755
new mode 100644
diff --git a/helper-scripts/nextcloud.sh b/helper-scripts/nextcloud.sh
old mode 100755
new mode 100644
diff --git a/helper-scripts/reset-learns.sh b/helper-scripts/reset-learns.sh
old mode 100755
new mode 100644
```
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
"iptables -L -vn":
"Chain INPUT (policy ACCEPT 7782K packets, 456M bytes)
 pkts bytes target     prot opt in     out     source               destination         
7782K  456M MAILCOW    all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 489K  151M MAILCOW    all  --  *      *       0.0.0.0/0            0.0.0.0/0           
 489K  151M DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
 489K  151M DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0           
 465K  143M ACCEPT     all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
 6788  456K DOCKER     all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0           
17351 7788K ACCEPT     all  --  br-mailcow !br-mailcow  0.0.0.0/0            0.0.0.0/0           
 6572  444K ACCEPT     all  --  br-mailcow br-mailcow  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 11M packets, 751M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.249         tcp dpt:6379
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.9           tcp dpt:8983
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.10          tcp dpt:3306
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.11          tcp dpt:5443
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.11          tcp dpt:5269
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.11          tcp dpt:5222
    3   160 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.3           tcp dpt:587
   46  2744 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.3           tcp dpt:465
   20  1172 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.3           tcp dpt:25
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:12345
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:4190
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:995
    3   160 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:993
    1    40 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:143
    1    60 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:110
  122  6358 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.14          tcp dpt:443
    5   244 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.14          tcp dpt:80

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
17351 7788K DOCKER-ISOLATION-STAGE-2  all  --  br-mailcow !br-mailcow  0.0.0.0/0            0.0.0.0/0           
 489K  151M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 DROP       all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0           
17351 7788K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 489K  151M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain MAILCOW (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REJECT     all  --  *      *       212.70.149.69        0.0.0.0/0            reject-with icmp-port-unreachable"

"ip6tables -L -vn":
"Chain INPUT (policy ACCEPT 697 packets, 46328 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  697 46328 MAILCOW    all      *      *       ::/0                 ::/0                

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 104K   87M MAILCOW    all      *      *       ::/0                 ::/0                
 105K   87M DOCKER-USER  all      *      *       ::/0                 ::/0                
 105K   87M DOCKER-ISOLATION-STAGE-1  all      *      *       ::/0                 ::/0                
 101K   87M DOCKER     all      *      br-mailcow  ::/0                 ::/0                
96886   86M ACCEPT     all      *      br-mailcow  ::/0                 ::/0                 ctstate RELATED,ESTABLISHED
 3359  562K ACCEPT     all      br-mailcow !br-mailcow  ::/0                 ::/0                
 3769  245K ACCEPT     all      br-mailcow br-mailcow  ::/0                 ::/0                

Chain OUTPUT (policy ACCEPT 591 packets, 40300 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:110
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:143
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:4190
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:993
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:995
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::3  tcp dpt:25
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::3  tcp dpt:465
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::3  tcp dpt:587
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::d  tcp dpt:5222
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::d  tcp dpt:5269
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::d  tcp dpt:5443

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 3359  562K DOCKER-ISOLATION-STAGE-2  all      br-mailcow !br-mailcow  ::/0                 ::/0                
 105K   87M RETURN     all      *      *       ::/0                 ::/0                

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all      *      br-mailcow  ::/0                 ::/0                
 3359  562K RETURN     all      *      *       ::/0                 ::/0                

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 105K   87M RETURN     all      *      *       ::/0                 ::/0                

Chain MAILCOW (2 references)
 pkts bytes target     prot opt in     out     source               destination   "
"iptables -L -vn -t nat":
"Chain PREROUTING (policy ACCEPT 13760 packets, 2149K bytes)
 pkts bytes target     prot opt in     out     source               destination         
  259 14274 DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 26 packets, 3720 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 3151K packets, 189M bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 3157K packets, 189M bytes)
 pkts bytes target     prot opt in     out     source               destination         
 2209  150K SNAT       all  --  *      *       172.22.1.0/24       !172.22.1.0/24        to:172.16.20.12
    0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
  121  8520 MASQUERADE  all  --  *      !br-mailcow  172.22.1.0/24        0.0.0.0/0           
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.249         172.22.1.249         tcp dpt:6379
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.9           172.22.1.9           tcp dpt:8983
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.10          172.22.1.10          tcp dpt:3306
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.11          172.22.1.11          tcp dpt:5443
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.11          172.22.1.11          tcp dpt:5269
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.11          172.22.1.11          tcp dpt:5222
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.3           172.22.1.3           tcp dpt:587
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.3           172.22.1.3           tcp dpt:465
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.3           172.22.1.3           tcp dpt:25
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:12345
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:4190
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:995
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:993
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:143
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:110
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.14          172.22.1.14          tcp dpt:443
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.14          172.22.1.14          tcp dpt:80

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0           
    0     0 RETURN     all  --  br-mailcow *       0.0.0.0/0            0.0.0.0/0           
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:7654 to:172.22.1.249:6379
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:18983 to:172.22.1.9:8983
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:13306 to:172.22.1.10:3306
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:5443 to:172.22.1.11:5443
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:5269 to:172.22.1.11:5269
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:5222 to:172.22.1.11:5222
    3   160 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:587 to:172.22.1.3:587
   47  2804 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:465 to:172.22.1.3:465
   20  1172 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:25 to:172.22.1.3:25
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:19991 to:172.22.1.250:12345
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:4190 to:172.22.1.250:4190
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:995 to:172.22.1.250:995
    3   160 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:993 to:172.22.1.250:993
    1    40 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:143 to:172.22.1.250:143
    1    60 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:110 to:172.22.1.250:110
  123  6418 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            172.16.20.12         tcp dpt:443 to:172.22.1.14:443
    5   244 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            172.16.20.12         tcp dpt:80 to:172.22.1.14:80"

"ip6tables -L -vn -t nat":
"Chain PREROUTING (policy ACCEPT 1244 packets, 101K bytes)
 pkts bytes target     prot opt in     out     source               destination         
   28  2120 DOCKER     all      *      *       ::/0                 ::/0                 ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 27 packets, 2040 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 6 packets, 576 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER     all      *      *       ::/0                !::1                  ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 770 packets, 61696 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  453 37374 SNAT       all      *      *       fd4d:6169:6c63:6f77::/64 !fd4d:6169:6c63:6f77::/64  to:2001:4ba0:92c1:4c:ffff:ffff:20:20
    0     0 MASQUERADE  all      *      br-mailcow  ::/0                 ::/0                 ADDRTYPE match dst-type LOCAL
   57  5317 MASQUERADE  all      *      !br-mailcow  fd4d:6169:6c63:6f77::/64  ::/0                
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:110
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:143
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:4190
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:993
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:995
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::3  fd4d:6169:6c63:6f77::3  tcp dpt:25
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::3  fd4d:6169:6c63:6f77::3  tcp dpt:465
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::3  fd4d:6169:6c63:6f77::3  tcp dpt:587
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::d  fd4d:6169:6c63:6f77::d  tcp dpt:5222
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::d  fd4d:6169:6c63:6f77::d  tcp dpt:5269
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::d  fd4d:6169:6c63:6f77::d  tcp dpt:5443

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all      br-mailcow *       ::/0                 ::/0                
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:110 to:[fd4d:6169:6c63:6f77::f]:110
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:143 to:[fd4d:6169:6c63:6f77::f]:143
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:4190 to:[fd4d:6169:6c63:6f77::f]:4190
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:993 to:[fd4d:6169:6c63:6f77::f]:993
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:995 to:[fd4d:6169:6c63:6f77::f]:995
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:25 to:[fd4d:6169:6c63:6f77::3]:25
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:465 to:[fd4d:6169:6c63:6f77::3]:465
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:587 to:[fd4d:6169:6c63:6f77::3]:587
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:5222 to:[fd4d:6169:6c63:6f77::d]:5222
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:5269 to:[fd4d:6169:6c63:6f77::d]:5269
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:5443 to:[fd4d:6169:6c63:6f77::d]:5443"

- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.
Output:
"sudo docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254
151.101.193.69
151.101.129.69
151.101.1.69
151.101.65.69"

**Comment by dragoangel** [comment]
Your git diff show that your permission are incorrect. Such stuff can result in many errors. Failure of service start is one of them. Obviously the case: your postfix is dead, reasons can be many, from wrong user:group - permission that service can't read own config and start to wrong network setup and so on. You can try run `docker-compose postfix-mailcow postfix check` to get diagnostics of failure reason.

To note: you not provide iptables and dig output which also can be a reason.

If this fresh (Zero-setup) my recommendation is to start from scratch, delete all mailcow data and volumes, git checkout again and up the stack as I think you messed your setup or not followed docs when done initial setup.

**Comment by kreditor0815** [comment]
Hi @dragoangel,

thanks for the quick response. Is it possible to get further support on that? I'm using this instance for over a year now and would like to keep that running.
I just edited iptables and dig output in my previous post.
"docker-compose exec postfix-mailcow postfix check" does not give me any output.
Is there a way to fix permissions on the files?

**Comment by dragoangel** [comment]
Better reask stuff on telegram, there much more people who can help and in realtime. Dns resolving working. I not pro at iptables, for me on first look they fine. About permissions I don't know easy fix, I only see that you have 644 when needed 755 over list of files, this can be not all issues with permission that you have. You need reset them to correct value. My recommendation is to setup additional vm (locally as example) and go over it to compare your actual and default mailcow user:group and unix permission mode and fix it folder per folder, file per file.

**Comment by dragoangel** [comment]
About postfix check that not return anything can be because your docker is shutdown, try  `docker-compose restart postfix-mailcow; docker-compose exec postfix-mailcow postfix check` and hopefully it will not die in 1s and will return some output, but no warranty on it.

**Comment by dragoangel** [comment]
And: if you say you have setup that was working for a year, you maybe have backups of homedir where all was working?;) And what you done before it break?

**Comment by kreditor0815** [comment]
I dont have telegram - is there another support channel?
I just did "docker-compose restart postfix-mailcow; docker-compose exec postfix-mailcow postfix check":
"Restarting mailcowdockerized_postfix-mailcow_1 ... done
postfix/postfix-script: warning: symlink leaves directory: /etc/postfix/./makedefs.out"

Yeah i ... kinda have backups. 3 hours ago i noticed, that i have a backup gap of acout 5 days :(
This is the way i need to go when im not able to fix that problem. Thus im hoping to get some help here to fix this particular problem im currently facing.

Thank you very much for your help. 
Tomorrow i'll try setting the file modes.

**Comment by dragoangel** [comment]
All links on home page (readme.md) of mailcow repo are available :)

**Comment by dragoangel** [comment]
Your error aren't fatal, they ok. Try run command one by one, separately, without `;`. If it not find any issues, try send mail :)

**Comment by kreditor0815** [comment]
I just fixed the file modes and my diff to origin/master now looks like this:
"diff --git a/data/conf/sogo/sogo.conf b/data/conf/sogo/sogo.conf
index 2513f496..5f673a04 100644
--- a/data/conf/sogo/sogo.conf
+++ b/data/conf/sogo/sogo.conf
@@ -26,10 +26,10 @@
     // Domains are isolated, you can define visibility options here.
     // Example:
 
-    // SOGoDomainsVisibility = (
-    //  (domain1.tld, domain5.tld),
-    //  (domain3.tld, domain2.tld)
-    // );
+    SOGoDomainsVisibility = (
+     (-this-got-redacted-again)
+    //  (homezone.xyz, )
+    );
 
     // self-signed is not trusted anymore
     SOGoSieveServer = "sieve://dovecot:4190/?TLS=YES&tlsVerifyMode=none";"

But - as you was expecting - this did not fix my problems.
I also did a "sudo docker exec mailcowdockerized_postfix-mailcow_1 postfix start" and after that i got some log lines:
"27.03.2021, 21:13:53 | info | the Postfix mail system is running: PID: 131
-- | -- | --
27.03.2021, 21:13:50 | info | daemon started -- version 3.4.14, configuration /etc/postfix
27.03.2021, 21:13:50 | info | starting the Postfix mail system"

But i also get a couple of errors/rejects that i think should not be there:
"27.03.2021, 21:21:20	info	NOQUEUE: reject: RCPT from unknown[167.89.101.199]: 454 4.7.1 <this-is-my-github-account-mail-address>: Relay access denied; from=<bounces+848413-1326-sec_esc=dan-mueller.de@sgmail.github.com> to=<this-is-my-github-account-mail-address> proto=ESMTP helo=<o8.sgmail.github.com>
27.03.2021, 21:21:20	info	connect from unknown[167.89.101.199]
27.03.2021, 21:20:13	info	statistics: max cache size 2 at Mar 27 21:14:51
27.03.2021, 21:20:13	info	statistics: max connection count 1 for (smtp:212.227.17.12) at Mar 27 21:14:44
27.03.2021, 21:20:13	info	statistics: max connection rate 1/60s for (smtp:212.227.17.12) at Mar 27 21:14:44
27.03.2021, 21:16:53	info	disconnect from unknown[167.89.101.198] ehlo=2 starttls=1 mail=1 rcpt=0/1 commands=4/5
27.03.2021, 21:16:53	info	lost connection after RCPT from unknown[167.89.101.198]
27.03.2021, 21:16:53	info	NOQUEUE: reject: RCPT from unknown[167.89.101.198]: 454 4.7.1 <this-is-my-github-account-mail-address>: Relay access denied; from=<bounces+848413-1326-sec_esc=dan-mueller.de@sgmail.github.com> to=<this-is-my-github-account-mail-address> proto=ESMTP helo=<o7.sgmail.github.com>
27.03.2021, 21:16:52	info	connect from unknown[167.89.101.198]
27.03.2021, 21:14:53	info	disconnect from unknown[192.254.113.101] ehlo=2 starttls=1 mail=1 rcpt=0/1 commands=4/5
27.03.2021, 21:14:53	info	lost connection after RCPT from unknown[192.254.113.101]
27.03.2021, 21:14:53	info	NOQUEUE: reject: RCPT from unknown[192.254.113.101]: 454 4.7.1 <this-is-my-github-account-mail-address>: Relay access denied; from=<bounces+848413-1326-sec_esc=dan-mueller.de@sgmail.github.com> to=<this-is-my-github-account-mail-address> proto=ESMTP helo=<o6.sgmail.github.com>
27.03.2021, 21:14:51	info	connect from unknown[192.254.113.101]
27.03.2021, 21:14:44	info	disconnect from unknown[212.227.17.12] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 quit=1 commands=5/7
27.03.2021, 21:14:44	info	NOQUEUE: reject: RCPT from unknown[212.227.17.12]: 454 4.7.1 <WBD_Pich_Acc@dan-mueller.de>: Relay access denied; from=<-here-is-a-testmail-sender> to=<-here-was-the-destination-of-my-testmail> proto=ESMTP helo=<mout.web.de>
27.03.2021, 21:14:44	info	connect from unknown[212.227.17.12]"

When I fire "sudo docker-compose exec postfix-mailcow postfix check" I only get the line "postfix/postfix-script: warning: symlink leaves directory: /etc/postfix/./makedefs.out".

But I'm still not able to send any mail.

I really do believe that there is a problem with my postfix, but I dont havy any clue how to diagnose this further.

**Comment by dragoangel** [comment]
Logs that you see are normal. They mean that someone try use your smtp as relay, that's usual on web, and they denied. I have no more idea what going on with your postfix else, try send over mail app, not sogo.

**Comment by Tokukarin** [comment]
~~I'm unsure but I think this is based upon the network environment.~~
~~I did setup a clean ubuntu 18.04 server and installed mailcow and I got the same error ( not allowed in state 1 )~~

~~My environment consists of a pi-hole that I bypassed for the test but it still failed.~~
~~Postfix doesn't throw any errors for me, only one warning:~~
~~`"postfix/postfix-script: warning: symlink leaves directory: /etc/postfix/./makedefs.out"`~~
~~but that path doesn't even exist for me.~~

Did you already find out the issue? I think communicating this over Telegram is BS, the answer should be documented right next to the project, what would be exactly here.

Edit & answer:

Everything Bullshit above. I just debugged all logs and found out this error occurs If your "mailcow_hostname" in the mailcow.conf appears to not be an FQDN.

Changed it to my domain (mail.example.com) restarted and worked again.
This was pretty confusing because I migrated from an old version and that one was working with my IP in the mailcow.conf.

**Comment by dragoangel** [comment]
@Tokukarin  Mailcow fqdn should be fqdn, it NEVER should be an ip 🤦‍♂️

**Comment by Tokukarin** [comment]
@dragoangel please think before writing code. The old ./generate_config.sh did not accept my FQDN, I had to set it to an IP and then manually changing it back to my FQDN and when I tried to change something I had to restart and change it to my IP and then again back and restart again.

**Comment by dragoangel** [comment]
@Tokukarin open https://github.com/mailcow/mailcow-dockerized/blame/master/generate_config.sh#L49 and https://github.com/mailcow/mailcow-dockerized/blame/master/update.sh#L177 Look at last modification date and at code. This validation check that you have at least two dots at FQDN. Any FQDN contain at least 2 `.`, e.g.: `host.example.com` and some should even have more, e.g.: `host.example.com.pl`. If you say that you put there your domain and it fail to accept it then basically you was tried to use there not FQDN, but domain name (e.g.: `example.com`), which isn't correct, as well as IP there.

Please read descriptions, docs or use support if you have issues, but not blame someone due to fact you not taking care about your part of setup.

**Comment by Tokukarin** [comment]
@dragoangel yeah you idiot, in every IP there are at least two dots. what a freaking dumb check.

**Comment by dragoangel** [comment]
@Tokukarin if people not understand what they doing they will always find way to break their setup and blame everyone except themself.

**Comment by Tokukarin** [comment]
@dragoangel I never blamed anyone until you insulted me, I tried to solve this issue.

But yes now you'll get one, without you as contributor maybe I wouldn't even be here in the first place.

**Comment by waja** [comment]
He guys, keep calm! Offending each other results in bad karma. Keep politely.
