### ISSUE TITLE
System Information does not work

### ISSUE THREAD

**Issue by qupfer** [mailcow/mailcow-dockerized#4259]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

Hi,
If I open the System Information view (https://$HOSTNAME/debug.php), its not loading. 
![grafik](https://user-images.githubusercontent.com/2614431/131639764-c5994a1c-8919-463a-aaaa-78db3e5a57e8.png)

If I switch back to the main panel, I receive the following error:

> An unknown error occured: TypeError Object ( [message:protected] => explode(): Argument #2 ($string) must be of type string, array given [string:Error:private] => [code:protected] => 0 [file:protected] => /web/debug.php [line:protected] => 42 [trace:Error:private] => Array ( [0] => Array ( [file] => /web/debug.php [line] => 42 [function] => explode [args] => Array ( [0] => , [1] => Array ( [msg] => __init__() got an unexpected keyword argument 'disable_buffering' [type] => danger ) ) ) ) [previous:Error:private] => )
![grafik](https://user-images.githubusercontent.com/2614431/131640017-036226f8-7da2-4ae6-a073-fbd4a0f92508.png)

I updated it via update.sh from the git master branch just before writing this issue . 

## Logs
Maybe I'm to slow, but can't see any  "error" in the logs of any contrainer. 

## Reproduction
Just open https://$HOSTNAME/debub and then go back to https://$HOSTNAME

## System information

| Question | Answer |
| --- | --- |
| My operating system | Debian 11 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | Docker on "Hetzner Cloud" |
| Server/VM specifications (Memory, CPU Cores) | 4 GB, 2 Cores |
| Docker Version (`docker version`) | 20.10.8 |
| Docker-Compose Version (`docker-compose version`) |  1.29.2, build 5becea4 |
| Reverse proxy (custom solution) | No |

- except the hostname, no changes
- no firewall
- no DNS problems

**Comment by zugnet643** [comment]
Same issue here.

**Comment by obakuhl** [comment]
Same here. Recently updated (today noon).

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | VirtualBox |
| Server/VM specifications (Memory, CPU Cores) | 8 GB, 2 Cores |
| Docker Version (`docker version`) | 20.10.3 |
| Docker-Compose Version (`docker-compose version`) | 1.29.2, build 5becea4c |
| Reverse proxy (custom solution) | Yes (nginx) |

**Comment by andryyy** [comment]
@feldsam has fixed it, i think

**Comment by awooooool** [comment]
> 
> 
> @feldsam has fixed it, i think

I don't think so. I've tried adding his lines, yet /debug still stuck. I think the issue is in the line which nginx needs to query disk usage through dockerapi container.

**Comment by andryyy** [comment]
Oh, just seen it. Yes. Will fix it.

**Comment by awooooool** [comment]
Might be the dockerapi itself that's acting up. I'm not really proficient with Python so can't really tell.

**Comment by niiyankee** [comment]
I can confirm this is a bug that needs to be fixed.

**Comment by andryyy** [comment]
I cannot reproduce it anywhere. Not a single machine with that machine. I'd need full access to a machine where that happens to help.

**Comment by andryyy** [comment]
Are you on the very latest commit?

**Comment by awooooool** [comment]
> Are you on the very latest commit?

I just updated today

**Comment by andryyy** [comment]
When?

**Comment by zugnet643** [comment]
I updated just right now, seems to work again, thanks!

**Comment by MAGICCC** [comment]
> 
> 
> > Are you on the very latest commit?
> I just updated today


On which commit are you?

**Comment by obakuhl** [comment]
I updated today at 12:47:04.

**Comment by MAGICCC** [comment]
Can you update again?
Should be fixed in https://github.com/mailcow/mailcow-dockerized/commit/bdf601ff2833442b3c2e07a548fe12d15289867b

**Comment by feldsam** [comment]
Error on screenshot is different. It is on line 42, my fix is on line 105. On line 42 array is excepted because direct pass to json_encode. There should be check or cast again

**Comment by feldsam** [comment]
We use PHP8, but application doesn't even use features provided in PHP 7.x. We should do big refactoring of PHP code.

**Comment by obakuhl** [comment]
I have made an update again. Now it works.

**Comment by feldsam** [comment]
you don't hit error, because other path in app was selected, but error was not fixed. It is on this line      https://github.com/mailcow/mailcow-dockerized/blob/107c8ed22961993b9b0b7d961c362ece311ddd9f/data/web/debug.php#L42

**Comment by awooooool** [comment]
After updating today, it's fixed. Taking a closer look, there's an update to mailcow/dockerapi. The bug happened in 1.38. Fixed in 1.39.

**Comment by feldsam** [comment]
The problem was with dockerapi doesn't return proper JSON, so debug ends with an ugly error.

**Comment by niiyankee** [comment]
<img width="1348" alt="Screen Shot 2021-09-02 at 8 44 10 AM" src="https://user-images.githubusercontent.com/89874872/131846237-1dfbaaeb-68f0-4cab-8959-12eea5e9cc4f.png">
<img width="1210" alt="Screen Shot 2021-09-02 at 8 43 38 AM" src="https://user-images.githubusercontent.com/89874872/131846239-c401f1f9-f0bc-476f-b8fa-e464c971372b.png">
This still does not work after running ./update.sh

**Comment by qupfer** [comment]
cache/restart problem?

**Comment by andryyy** [comment]
TZ=US is not valid, use a correct time zone. :)

**Comment by niiyankee** [comment]
> TZ=US is not valid, use a correct time zone. :)

Thanks for pointing this out to me. My mistake and have corrected and rebooted but the error message still points to TZ=US. I have updated the TimeZone in mailcow.conf and wondering if there's another file I need to update? It looks like the /opt/mailcow-dockerized/data/web/debug.php is fetching TZ from the mailcow.conf file so my changes should work after reboot.

**Comment by awooooool** [comment]
> 
> 
> > TZ=US is not valid, use a correct time zone. :)
> 
> Thanks for pointing this out to me. My mistake and have corrected and rebooted but the error message still points to TZ=US. I have updated the TimeZone in mailcow.conf and wondering if there's another file I need to update? It looks like the /opt/mailcow-dockerized/data/web/debug.php is fetching TZ from the mailcow.conf file so my changes should work after reboot.

`docker-compose up -d --force-recreate` maybe?

**Comment by niiyankee** [comment]
> `docker-compose up -d --force-recreate` maybe?

That worked! Thank you so much everyone for the quick responses!
