### ISSUE TITLE
SoGO / CalDav: Personal Calendar issue on Mac OS 13

### ISSUE THREAD

**Issue by saibotk** [mailcow/mailcow-dockerized#4897]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

There is currently a bug in mac OS 13 (?) which causes the Calendar.app to ignore calendars, that begin with lowercase letters (in their internal identifier).

This seems to be the case for the default (unremovable) calendar in SoGO.

More information can be found in their respective issue: https://bugs.sogo.nu/view.php?id=5639

It would be good to discuss, if we want to pull in 5.8.0 nightly, with this fix included.
There is only one other small commit that would be included and it seems reasonable to consider this stable, but im open to your suggestions.

**Comment by mkuron** [comment]
Yes, we‘ll definitely want https://github.com/Alinto/sogo/commit/03e6d0012bc0d6ba4d8cb427f8d904a75d9ce036 in Mailcow ASAP. @DerLinkman, can you please update the SOGo image to the latest nightly? I guess our SOGo image is currently 12 days old (#4877), but this fix was merged upstream just 5 days ago.

**Comment by DerLinkman** [comment]
Then I'll publish 2022-11b today with that fix.

**Comment by MAGICCC** [comment]
Reopened because theres still another issue based on https://bugs.sogo.nu/view.php?id=5639
Maybe need to rerebuild the image again - no need for new release imho

**Comment by DerLinkman** [comment]
Jup, new image will come when it's fixed.

**Comment by PeterHagen** [comment]
Is this related to not being able to set a color to a calendar anymore? When I change the color, I'll get an explanation mark icon on the calendar. When I click it, the following message appears:

> ## Your calendar couldn’t be updated.
>
> The calendar “Persoonlijke agenda” failed to update with an unexpected error.
> 
> The request for “Persoonlijke agenda” in account “....” failed.
>
> The server responded with “400”

**Comment by MAGICCC** [comment]
Yes see https://bugs.sogo.nu/view.php?id=5639#c16525, it seems to be fixed in their nightly builds, but some other things not

**Comment by skurfuerst** [comment]
Hey everybody, @MAGICCC @PeterHagen @DerLinkman 

I have updated update my mailcow-dockerized-sogo to the latest SoGo nightly via:

```
docker-compose -f docker-compose.yml -f helper-scripts/docker-compose.override.yml.d/BUILD_FLAGS/docker-compose.override.yml -f docker-compose.override.yml build sogo-mailcow
docker-compose up -d
```

... and this fixed the issues for us - so it seems the latest SoGo Nightly actually solves the problems :) 

So delegation works again in Mac OS; Colors can be set, looks all good from my side.

Can you test that, and if it works, maybe release a new Mailcow-Dockerized version, so it is fixed for more people?

All the best,
Sebastian

**Comment by PeterHagen** [comment]
I would like to test it, but I currently don't have a test environment. I'll try to set one up

**Comment by skurfuerst** [comment]
FYI @PeterHagen  - unfortunately while the original problem is fixed, some other followup problems still persist :( see https://bugs.sogo.nu/view.php?id=5639 .

All the best,
Sebastian

**Comment by DerLinkman** [comment]
Could someone try the latest nightly? And approve that the issue has been fixed?

I don't have any macOS to test here.

Thanks @skurfuerst for fixing btw.

**Comment by mokusone** [comment]
I've tried today with the nightly build like mentioned before

docker compose down
docker compose -f docker-compose.yml -f helper-scripts/docker-compose.override.yml.d/BUILD_FLAGS/docker-compose.override.yml -f docker-compose.override.yml build sogo-mailcow
docker compose up -d

but still have the issue, that if I try to connect from my macros OS 13.1 to malcow it always create new Kalender and my personal calendar isn't shown.

**Comment by PeterHagen** [comment]
Yesterday I updated to the latest Mailcow release and the issue is resolved for me

**Comment by saibotk** [comment]
I also do not have any issues anymore

**Comment by mokusone** [comment]
but my image is:

mailcow/sogo:1.114	518.1 MB	2023-01-22 20:33:51

did I something wrong?

**Comment by saibotk** [comment]
You could describe your issue, since it is not clear what problem you are facing. This thread outlines multiple issues that came up along the way.

**Comment by mokusone** [comment]
> You could describe your issue, since it is not clear what problem you are facing. This thread outlines multiple issues that came up along the way.

I still have the issue, when I connect my apple calendar from MacBook with macOS13.1 over caldav that Iit is created a new calendar and my personal one is not visible.

**Comment by skurfuerst** [comment]
FYI @saibotk , the issue still seems to persist, as I have thoroughly documented in the SOGO Bugtracker at https://bugs.sogo.nu/view.php?id=5639#c16583 - I have the same behavior inside Mailcow, and inside demo.sogo.nu.

All the best,
Sebastian

**Comment by thomseno** [comment]
There seems to be a working version now [https://bugs.sogo.nu/view.php?id=5639#c16624](https://bugs.sogo.nu/view.php?id=5639#c16624). Any plans for an update?

**Comment by DerLinkman** [comment]
We can release a Update tomorrow. If more users could confirm that it work would be helpful.

**Comment by saibotk** [comment]
I can confirm it works, and on Mac OS it also does not show any error anymore.

While it seems to sync again on iOS and iPadOS it still shows an error icon, sadly its much harder to get the actual error on those devices :(

**Comment by thomseno** [comment]
Finally, my and the delegated calendars are there again in macOS. Thanks to everyone.

**Comment by mokusone** [comment]
it works for personal calendar and second calendar... but shared / global / group-calendar didn't appear in my calendar anymore

**Comment by DerLinkman** [comment]
Please report it to alinto. We are not SOGo

> it works for personal calendar and second calendar... but shared / global / group-calendar didn't appear in my calendar anymore

**Comment by ffried** [comment]
@DerLinkman @MAGICCC The upstream issue has been resolved differently, which should also fix issues with the upcoming macOS Sonoma. Any chance you can deploy a new SoGO version?

**Comment by MAGICCC** [comment]
Hi @ffried 
Can you try to use mailcow/sogo:pr-4897 as image? It's based on Version 5.8.4 (@sogo-build.alinto.int 202309050509)

**Comment by ffried** [comment]
@MAGICCC That's gonna be difficult - we're using a managed Mailcow instance. 🙃

**Comment by MAGICCC** [comment]
Hah ok, then you may wait for @DerLinkman or @FreddleSpl0it to update the managed solution

**Comment by ffried** [comment]
@MAGICCC Thanks!
@DerLinkman @FreddleSpl0it Any chance to get this deployed _before_ the public release of macOS Sonoma on 26.09.?

I've just installed the release candidate (released yesterday evening) and the personal calendar is gone again.

**Comment by ffried** [comment]
@DerLinkman @FreddleSpl0it Any news on this? macOS Sonoma's release build was slightly different than the release candidate, but (unsurprisingly) still has the same Calendar.app behavior.

**Comment by ffried** [comment]
Fixed by #5433. 
Thanks @DerLinkman!
