### ISSUE TITLE
Latest dovecot shows up in watchdog

### ISSUE THREAD

**Issue by markirb** [mailcow/mailcow-dockerized#897]
Hi,

using the latest master images (upgraded today), i found that the dovecot is reported periodically as unhealthy (gets -10 score) and afterwards recovers again (+1,....).
So it is not restarted.

I manually did a 
`while true; do /usr/lib/nagios/plugins/check_imap -4 -H 172.22.1.2 -p 143 -e "OK "; sleep 1; done`
which shows periods of 
`connect to address 172.22.1.2 and port 143: Connection refused`
which seems to be the issue.
Dovecot logs do not show anything suspicious.
Anybody else having this problem?

**Comment by andryyy** [comment]
The IP is not static, watchdog discovers the new IP via API. So it is possible Dovecots IP changed after a restart (triggered by watchdog) and as a result you see "connection refused".

Did you run ./update.sh ? I think it was fixed with [this commit](https://github.com/mailcow/mailcow-dockerized/commit/ceef6d6fd3e7f8fb2c57d8afbc733cf4049cc4c8#diff-a77177604f8ed3cf75b83efe774c8f9bR170).

**Comment by markirb** [comment]
Jeah, sorry, of course the IP is not static, its just the one in my case... 😄  Did not mean to confuse you.

It seems to coincied with 

> dovecot-mailcow_1    | Jan 14 18:37:01 mail CRON[1001]: pam_unix(cron:session): session opened for user root by (uid=0)
> 
> dovecot-mailcow_1    | Jan 14 18:37:01 mail CRON[1003]: (root) CMD (  /usr/local/bin/imapsync_cron.pl)
> 
> dovecot-mailcow_1    | Jan 14 18:37:01 mail CRON[1001]: pam_unix(cron:session): session closed for user root

**Comment by andryyy** [comment]
No, these lines are fine. Do you upgrade by running ./update.sh ? Is your watchdog image up to date?

**Comment by markirb** [comment]
Did not use update.sh, but using latest watchdog image 1.12.
But now that i pulled it again, it pulled some different image 😕 ? Even though the one i was using was newer? Can you enlighten me?
I'm trying the other one now... lets see.

Edit: still seeing error, again same time as the cronjob executes on dovecot

**Comment by andryyy** [comment]
Probably just rebuilt by Travis. :-)

Can you please uncomment "command" in docker-compose.yml?

    watchdog-mailcow:
      image: mailcow/watchdog:1.12
      # Debug
      #command: /watchdog.sh <- uncomment

And run docker-compose up -d afterwards. Just wait for watchdog to restart Dovecot and paste the logs from "docker-compose logs watchdog-mailcow" to paste.ee or somewhere else. :-)

**Comment by markirb** [comment]
Same same... (https://paste.ee/p/ejfPX)
Relevant part:
```
watchdog-mailcow_1   | connect to address 172.22.1.2 and port 24: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.000 sec. response time|time=0.000111s;;;0.000000
watchdog-mailcow_1   | connect to address 172.22.1.2 and port 993: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.2 and port 143: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.2 and port 10001: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.2 and port 4190: Connection refused
watchdog-mailcow_1   | Rspamd settings check succeeded
watchdog-mailcow_1   | HTTP OK: HTTP/1.0 200 OK - 340965 bytes in 0.004 second response time |time=0.003959s;;;0.000000 size=340965B;;;0
watchdog-mailcow_1   | Uptime: 13400  Threads: 39  Questions: 46931  Slow queries: 0  Opens: 59  Flush tables: 1  Open tables: 53  Queries per second avg: 3.502|Connections=2981c;;; Open_files=25;;; Open_tables=53;;; Qcache_free_memory=65461296;;; Qcache_hits=18690c;;; Qcache_inserts=1741c;;; Qcache_lowmem_prunes=0c;;; Qcache_not_cached=4400c;;; Qcache_queries_in_cache=1455;;; Queries=46931c;;; Questions=30325c;;; Table_locks_waited=0c;;; Threads_connected=9;;; Threads_running=1;;; Uptime=13400c;;;
watchdog-mailcow_1   | Sun Jan 14 17:54:40 GMT 2018 Dovecot health level: 58% (14/24), health trend: -10
```

**Comment by markirb** [comment]
this might be a real networking issue here with latest docker update, not specifically with mailcow...

**Comment by andryyy** [comment]
Hmm. Can you try to stop all containers (docker-compose down) followed by a Docker restart?

Do you have Fail2ban installed on your host that maybe blocks watchdog?

**Comment by markirb** [comment]
No, there's no fail2ban.

But i did a complete reboot now, everything seems to work fine now... Really strange things, sorry for the hassle

**Comment by hachre** [comment]
I often have network issues as well after updating Docker. I've started doing reboots after Docker updates just like after Kernel updates for this reason.
