### ISSUE TITLE
User cannot login into admin interface after upgrade to dockerized

### ISSUE THREAD

**Issue by imp1sh** [mailcow/mailcow-dockerized#948]
After I upgraded some time ago from non-dockerized to dockerized I cannot login to the admin interface as a user any more. The users can login to the webmailer though.

I'm on ec51c8413fec1f8dc61e764534fffee89e56b13c.
kernel: 4.14.11-300.fc27.x86_64
OS: Fedora 27
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

What other information do you need to help me with this?

**Comment by PhoenixPeca** [comment]
Seems like you have not migrated your database properly. Please refer to this guide: https://mailcow.github.io/mailcow-dockerized-docs/migrate-mc014/

**Comment by imp1sh** [comment]
I used the exact same link for my migration. Everything works beside logging into the admin interface with user credentials.

**Comment by andryyy** [comment]
Hm, can you update your code, again?

**Comment by imp1sh** [comment]
With update my code you mean to run ./update.sh?
I did that already a couple of times after the update. I migrated in October 2017 or something like that.

**Comment by topelrapha** [comment]
Also have this problem:

With IMAP and SMTP no problems - UserUI login with error:

nginx-mailcow_1      | 2018/01/25 10:59:14 [error] 12#12: *35 FastCGI sent in stderr: "PHP message: mailcow UI: Invalid password for info@xx.de by xx.xx.xx.xx" while reading response header from upstream, client: xx.xx.xx, server: mail.topel-net.de, request: "POST / HTTP/2.0", upstream: "fastcgi://172.22.1.8:9000", host: "mail.topel-net.de", referrer: "https://xx.xx-xx.de/"
nginx-mailcow_1      | xx.xx.xx.xx- - [25/Jan/2018:10:59:14 +0000] "POST / HTTP/2.0" 200 15682 "https://xx.xx-xx.de/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"
php-fpm-mailcow_1    | 172.22.1.251 -  25/Jan/2018:10:59:14 +0000 "POST /index.php" 200
php-fpm-mailcow_1    | fd4d:6169:6c63:6f77::1 -  25/Jan/2018:10:59:14 +0000 "GET /inc/ajax/log_driver.php" 200
nginx-mailcow_1      | xx.xx.xx.xx- - [25/Jan/2018:10:59:14 +0000] "GET /inc/ajax/log_driver.php?type=danger&msg=Anmeldung+fehlgeschlagen HTTP/2.0" 200 0 "https://xx.xx-xx.de/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"

**Comment by andryyy** [comment]
This error was fixed a few days ago (or 1-2 weeks?).

**Comment by topelrapha** [comment]
Thanks for fast answer.
I updated via script a few minutes ago. So I think it should be fixed now?

But is still the problem.
Have you got an idea? Or a workaround how to fix it manually?

⁣Gesendet mit BlueMail ​

**Comment by andryyy** [comment]
Hm, sadly not. I'd need to check it via remote desktop, if possible. Did you migrate, too?

**Comment by imp1sh** [comment]
Now I'm on 59d32baf631738cffe75e77851ae08c0bca9fd25 and login still not working.
```
php-fpm-mailcow_1    | [28-Jan-2018 22:44:10] WARNING: [pool www] child 235 said into stderr: "NOTICE: PHP message: mailcow UI: Invalid password for user@domain.name by 2001:cccc:1111:1b:a144:e817:36e3:8ca3"
nginx-mailcow_1      | 2001:cccc:1111:1b:a144:e817:36e3:8ca3 - - [28/Jan/2018:22:44:10 +0000] "POST / HTTP/2.0" 200 15524 "https://www.another.domain.name/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36"
nginx-mailcow_1      | 2018/01/28 22:44:10 [error] 13#13: *38 FastCGI sent in stderr: "PHP message: mailcow UI: Invalid password for user@domain.name by 2001:cccc:1111:1b:a144:e817:36e3:8ca3" while reading response header from upstream, client: 2001:cccc:1111:1b:a144:e817:36e3:8ca3, server: my.server.name, request: "POST / HTTP/2.0", upstream: "fastcgi://172.22.1.10:9000", host: "www.another.domain.name", referrer: "https://www.another.domain.name/"
```

**Comment by andryyy** [comment]
You probably came from a non Docker mailcow without SOGo and SHA512-Crypt hashes.

**Comment by imp1sh** [comment]
Yes, I came from a non-docker mailcow with roundcube. What is the way to proceed?

**Comment by topelrapha** [comment]
My solution was to reset the password via admin panel in mailbox tab.

So it sets the correct password hash in database and problem should be solved 😉

**Comment by imp1sh** [comment]
Yes, that did the trick, thank you. This document should give a hint about that issue:
https://mailcow.github.io/mailcow-dockerized-docs/migrate-mc014/
